version: "3.7"
services:
  web:
    image: next_meal_planner
    container_name: mealPlannerWeb
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      backend:

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    hostname: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - ./pocketbase/pb_data:/pb_data
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      backend:

networks:
  backend:
    driver: bridge