name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.9.0
          run_install: true
      - name: Cypress run
        uses: cypress-io/github-action@v5 # use the explicit version number
        with:
          build: pnpm run build
          start: pnpm run pipeline
      - name: Upload Cypress Screenshots and Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |-
            cypress/screenshots
            cypress/videos
        if: ${{ failure() }}